services:
  coredns:
    image: coredns/coredns:latest
    volumes:
      - ./Corefile:/etc/coredns/Corefile
    command: -conf /etc/coredns/Corefile
    networks:
      default:
        ipv4_address: 172.25.10.10

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      default:
        ipv4_address: 172.25.10.11
  ubuntu:
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    dns: 172.25.10.10
    networks:
      - default
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16